# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 21:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_one', models.CharField(blank=True, max_length=50)),
                ('address_two', models.CharField(blank=True, max_length=50)),
                ('town', models.CharField(blank=True, max_length=20)),
                ('county', models.CharField(blank=True, max_length=20)),
                ('post_code', models.CharField(max_length=9)),
                ('home_tel', models.CharField(blank=True, max_length=25)),
                ('mobile_tel', models.CharField(blank=True, max_length=25)),
                ('email_shared', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_role', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='memberrole',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwbb_members.RoleType'),
        ),
    ]
