# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberrole',
            name='date_started_role',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
