# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0002_memberrole_date_started_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberrole',
            name='date_started_role',
        ),
        migrations.AlterField(
            model_name='member',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
