# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0003_auto_20160313_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='id_number',
            field=models.CharField(default='BBC02', max_length=50),
            preserve_default=False,
        ),
    ]
