# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0004_member_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='town',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
