# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-08 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nwbb_members', '0008_auto_20160425_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingOffence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('points', models.CharField(blank=True, max_length=10)),
                ('duration', models.IntegerField()),
                ('duration_details', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDrivingOffence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nwbb_members.DrivingOffence')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_offence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
