# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0009_drivingoffence_memberdrivingoffence'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivingoffence',
            name='max_points',
            field=models.IntegerField(blank=True, default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drivingoffence',
            name='min_points',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberdrivingoffence',
            name='points',
            field=models.IntegerField(default=-2),
            preserve_default=False,
        ),
    ]
