# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0010_auto_20160516_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingoffence',
            name='points',
        ),
    ]
