# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwbb_members', '0011_remove_drivingoffence_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivingoffence',
            name='duration_details',
            field=models.CharField(blank=True, choices=[(b'DOO', b'Depending on Offence'), (b'DOC', b'Depending on Conviction')], max_length=3),
        ),
        migrations.AlterField(
            model_name='memberdrivingoffence',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offences', to='nwbb_members.DrivingOffence'),
        ),
    ]
